app:
  topic: test_topic
  topic2: test_topic_2
  group:
    id: ${GROUP_ID}
  bootstrap:
    servers:
      config: ${BOOTSTRAP_SERVER_CONFIG}
  schema:
    registry:
      url:
        config: ${SCHEMA_REGISTRY_URL}